### ISSUE TITLE
User Support?

### ISSUE THREAD

**Issue by BrainZap** [airgap-it/airgap-wallet#11]
Could you please add some user support.  Discord would be nice.

While I have your attention:
I have a single coin with a balance.  When I click Exchange it tells me "you need at least two currencies in AirGap".  I've added other currencies, with 0 balance (via Vault on same device), but the Exchange is still telling me I need 2 currencies.  Does the app require a balance on two currencies, and if so, does the balance always need to be in the "target" currency?

Example:  AE -> BTC, does BTC balance need to be >0 to make this exchange?
Conversely, say I have AE and BTC balances and I want to do AE -> ETH, or BTC -> ETH.  Will the app require I already have a ETH balance > 0 to exchange?

![IMG_0311 1](https://user-images.githubusercontent.com/7952421/59554406-383d9f00-8f57-11e9-82ca-b03e0b760b2c.PNG)

![IMG_0312 1](https://user-images.githubusercontent.com/7952421/59554469-214b7c80-8f58-11e9-9b35-0bb7bac38950.PNG)

**Comment by AndreasGassmann** [comment]
Hi,

First of all, we do have a support channel on telegram. The link can be found on our website. We use telegram only for now, but if there is a large request for a discord, we can think about it.

Regarding the swap: The problem is that we currently do not support swapping AE at all. The exchange feature relies on an external provider (changelly) and we can only exchange currencies that they support. The error message is a bit misleading, we will change that to avoid this kind of confusion in the future.

Other than that it's pretty simple. You need 2 supported currencies, and only one of them (originating address) needs to have a balance.

Thanks for your feedback so far, it helps us a lot to hear the pain points of our users so we can make the app better :).

**Comment by BrainZap** [comment]
Thank you for clearing that up.  I will check out Telegram.

**Comment by rosspeili** [comment]
same issue in 2021

**Comment by AndreasGassmann** [comment]
We now have a discord server here: https://discord.com/invite/29SCWzTW7J

Regarding the second question, I answered that one in the reply above. Please open another issue with a detailed error description if it still doesn't work for you.
