### ISSUE TITLE
Question: Are these Images Generated/ Changabale

### ISSUE THREAD

**Issue by hofq** [airgap-it/airgap-wallet#124]
Hi, 
i saw these Images infront of every coin wallet and was wondering if you could customize them or how they get generated.

Is there any way to customize them?

Thanks for your Work :)
![IMG_20211219_044425](https://user-images.githubusercontent.com/54744977/146663182-b2415f1b-9ccc-4725-800d-521b20275b3a.jpg)

**Comment by AndreasGassmann** [comment]
Hi. These icons are commonly called "identicons". They can be used to quickly identify your address in different applications and websites. We used the most popular standard at the time (a few years ago), which I think was blockies: https://github.com/MyCryptoHQ/ethereum-blockies-base64

Nowadays, a variety of formats are being used on different websites. MetaMask is now using a different style for ETH accounts, Polkadot also has a completely custom style.

Because the purpose of the identicons is to identify an address, it is not possible to change or customise them, unless a new format is added that will result in a different identicon.

How would you like to change them? Just generating a different one (with different colors), or would you like to add something like an avatar?

**Comment by Kippenhof** [comment]
I was thinking more of a way to set some sort of avatar. Depending on how hard it is to implement something like that.

**Comment by AndreasGassmann** [comment]
An avatar could be set on the AirGap Wallet side, but it would be impossible (or impractical) to do it in AirGap Vault. So you would lose the "matching" between the Wallet and Vault identicons.

But I can see how this would be a useful feature because once you have a lot of accounts in the Wallet, it becomes crowded. So setting an avatar (and maybe even an alias for the address) would be great. We'll add it to the list.
