### ISSUE TITLE
Issue with BTC transfer from airgap.it wallet to Trust Wallet

### ISSUE THREAD

**Issue by jumpinjellybeans** [airgap-it/airgap-wallet#126]
I sent a BTC transaction from my airgap.it wallet to my Trust Wallet yesterday, and I still haven't received it yet. I've verified I sent the correct token to the correct address that supports that token. The transaction completed successfully and it's been close to 24hrs. Is this normal? Any guidance would be appreciated?

**Comment by AndreasGassmann** [comment]
Did you check the status of the transaction on a block explorer?

**Comment by jumpinjellybeans** [comment]
Hi @AndreasGassmann! I did and the BTC transaction finally showed up on Trustwallet yesterday. 3 questions: 

- I noticed you can set the transaction fees when transferring. Is there a fixed delivery time per fee?
- Also, do you have to manually account for the transaction fees when sending crypos? It seems airgap wallet does not automate transaction fee deductions. Any particular reason why?
- Is there a way to enable password protected access with the airgap wallet app?

Thank for the follow-up.

**Comment by AndreasGassmann** [comment]
1. No, the time it takes for a transaction to be included depends on the fees that everyone else sets. The higher your fee, the higher your chances. (Miners prefer txs with higher fees).

2. This is a bug in our BTC protocol, it just doesn't have high priority at the moment while we finish some other features.

3. No, only the Vault is PIN/password protected.

**Comment by jumpinjellybeans** [comment]
Thanks @AndreasGassmann! Since I'm a new btc user, my gut is to opt for the lowest tx fee for all btc transfers so as not to overpay. I'm just surprised it took 2 days for delivery. Is that normal? Would you happen to know any good resources that breakdown how tx fees affect delivery times or maybe even cryptos with minimal to no tx fees? Thanks for the recommendations as well - they are not as convenient if you're buying multiple cryptos.

**Comment by AndreasGassmann** [comment]
You can use the more advanced watch-only wallets for BTC and still use AirGap Wallet for all other currencies, that is no problem.

On the BTC network, 2 day delivery is nothing out of the ordinary. It all depends on the mempool   (= all pending transactions of the network) and where your fee is relative to all other fees. Calculating the optimal transaction fee is very hard because it is possible to set a fee, but just when you submit it, the network usage increases, which means that your transaction might not get included for a long time until the fee average comes down again. That's why the default settings usually add a small premium that hopefully ensures that your transaction is included in a few blocks.

If you don't care about the time of delivery (eg. you send the funds to one of your other accounts), then you can set the fee low and just wait longer. You can use this website to check the current mempool status and the recommended fee ratio: https://mempool.space/
Keep in mind that the fee rate for BTC is usually sat/vbyte, which means the total fee is dependent on the transaction size. In AirGap, for simplicity, we show the total fee instead of the sat/vbyte value. If you want to have fine granular control over this, then you can use a watch-only wallet and set the sat/vbyte value manually.

The transaction fees work differently on different networks (BTC, ETH, etc). While some networks have lower fees, this is usually due to them being more centralised or having less usage. Which cryptocurrency you should use depends on what you want to do with it. Simply using a cryptocurrency because it has lower fees doesn't really help you, you still have to make sure the recipient accepts that currency, or the applications you want to use (DEFI, etc.) support it.

**Comment by jumpinjellybeans** [comment]
Got it! Very helpful response. Thanks @AndreasGassmann
