### ISSUE TITLE
"It seems that no exchange could currently be set up, please excuse the inconvenience and try again later"

### ISSUE THREAD

**Issue by vindicatorr** [airgap-it/airgap-wallet#130]
https://github.com/airgap-it/airgap-wallet/blob/8d554d71f93462f4bd1f92fb2c4285ab49a2a474/src/assets/i18n/en.json#L432
I'm brand new to airvault (and only barely dabbled in crypto anyway), but created my vault and added 2 empty coins and synced to wallet... except wallet is showing progress bars for both coins.
If I click on "Exchange", I get the above error message.

EDIT0: API Health Check is also left spinning with "Checking API Health" and everything only saying "Loading".
EDIT1: Odd, I "pm installed-existing --user #" the app to another user profile and the Health Check worked there. I uninstalled it for the non-working user (along with cache/data clearing), and reinstalled it and it's still failing for that user.
Could I be missing some android/app setting? It's been given "network access" and "Wi-Fi data".

**Comment by AndreasGassmann** [comment]
Hi, thanks for reaching out.

I don't remember the exact logic of the "Exchange" screen, but it may be required for one of the coins to have a balance, because otherwise a swap isn't possible.

- Health Check: That one works for me (Polkadot and Kusama Explorers show up as down though, we'll look into it).

There shouldn't be any app settings that would prevent the health check from working that I'm aware of.

**Comment by vindicatorr** [comment]
I ended up building/running the master release in android studio after uninstalling the play-store version.
The Health Check worked.
So I stopped that app, uninstalled it, reinstalled the play-store version, deleted the cache/data, checked the Health Check... it worked. I dunno what was up and I can't replicate it, so I'll close the issue.

**Comment by AndreasGassmann** [comment]
That's weird. Happy to hear it did work for you. Feedback is always welcome :)
