### ISSUE TITLE
Chrome extensions: blocking Google account buttons

### ISSUE THREAD

**Issue by kmanx** [airgap-it/airgap-wallet#14]
Hi, today I encountered a new issue, which IMO is a little disturbing.

**How to produce:**
1. Install and enable AirGap Chrome extension.
2. Go to Google account settings > Security tab > 
3. Go to Manage devices (or Manage third party access)
4. Try to click on any button (not link),  it doesn't work.

So I had to disable the extension for now.

**Comment by pascuin** [comment]
Thanks for the report, I've encountered the same yesterday as well. Looks like Google is somehow blocking extension that are injecting code into websites.

In order to communicate with the website we inject web3 & the aeternity sdk into the site. This is also done by Metamask for example.

But we'll improve the injection handling in the  ear future and will definitely disable it for Google related websited.

**Comment by AndreasGassmann** [comment]
Because the chrome extension is no longer available, I will close this issue.

Hopefully in the near future we will have support for WalletConnect to replace the functionality of the chrome extension.
