### ISSUE TITLE
Account grouping?

### ISSUE THREAD

**Issue by databu** [airgap-it/airgap-wallet#15]
It would be nice to be able to group accounts in the wallet by secret, similar to the vault app.

**Comment by AndreasGassmann** [comment]
Hi, sorry for the late reply.

We'll look into this, but it would require a breaking change of our sync protocol between the wallet and the vault, so if we do it, we'll most likely wait until we have to introduce another breaking change.

I'll leave this issue open so we keep it on our radar.

Thanks for the suggestion!

**Comment by baltar** [comment]
Oh, I was thinking of this simply to easily see which account belongs to what secret. I thought that such a grouping could be done in the UI only, without affecting any protocol? 

Maybe I should describe where this suggestion is coming from. As it is right now, if I e.g. have 2 secrets, say 1 private and 1 for my business, and ETH accounts on both, my only way to distinguish them is by either recognising their public keys (easy to mix up) or their aprox. amounts.  It would be so much easier to see what is what if I can group them by the name of the secret, or even just by manually assigning names.

**Comment by AndreasGassmann** [comment]
Hey, sorry for the late reply, again.

It doesn't affect the individual coin protocols or blockchains, but it does affect the messages that are exchanged between Wallet and Vault. Because currently, only the necessary information like public key and coin type is exchanged. We will need to change this to also include some kind of "secret identifier". Because right now it's impossible to know which accounts originate from the same secret, so grouping is not possible.

Because we now have to update the messages for another feature, we'll also include this change. This means that hopefully soon this feature will be available. I'll keep you posted :).

**Comment by AndreasGassmann** [comment]
This has been implemented a while ago, you can now filter your addresses by secret in the Wallet as well. Thanks for suggesting this!
