### ISSUE TITLE
Set network to Binance Smart Chain

### ISSUE THREAD

**Issue by samos667** [airgap-it/airgap-wallet#55]
Hi I am new to cryptocurrency so please don't blame me for my mistakes.

The ethereum fees being extremely expensive I wanted to transfer my BNB from Binance by the BSC, not knowing the concept too much, and seeing that Airgap supported the BNB I said to myself that there was no problem .

Not receiving my BNB three to four hours after completing my transaction, I began to think that I might have done something stupid.

So I realize that beyond the fact that the wallet must manage the currency BNB, it must also be able to connect to the BSC network.

So what I would like to know is if it is possible to export my private key in order to integrate it into Metamask and thus be able to take advantage of my BNB.
Or if even better it would be possible to define the BSC network in Airgap.

Thank you in advance.

**Comment by AndreasGassmann** [comment]
Hi,

The 24 word mnemonic you have can be imported in MetaMask. I don't know how the Binance Chain works, and I'm not sure if MetaMask supports the native Binance Smart Chain. But you can try to import your 24 words in MetaMask and try.

Please note that you should never enter your 24 words into any other wallets, especially less secure wallets like MetaMask (Less secure because it's on Desktop, which frequently have malware on them). If you have a virus on your computer, it will be able to take your 24 words and steal all funds you have on it (BTC, ETH, DOT, etc.). So please be very careful where you enter those 24 words.

**Comment by AndreasGassmann** [comment]
If you need any more help, reach out to us via hi@airgap.it.

**Comment by flipflopflipp** [comment]
> Hi I am new to cryptocurrency so please don't blame me for my mistakes.
> 
> The ethereum fees being extremely expensive I wanted to transfer my BNB from Binance by the BSC, not knowing the concept too much, and seeing that Airgap supported the BNB I said to myself that there was no problem .
> 
> Not receiving my BNB three to four hours after completing my transaction, I began to think that I might have done something stupid.
> 
> So I realize that beyond the fact that the wallet must manage the currency BNB, it must also be able to connect to the BSC network.
> 
> So what I would like to know is if it is possible to export my private key in order to integrate it into Metamask and thus be able to take advantage of my BNB.
> Or if even better it would be possible to define the BSC network in Airgap.
> 
> Thank you in advance.

i have the same problem..

**Comment by AndreasGassmann** [comment]
We still don't have support for BSC in AirGap, but the solution I posted above should still work.

**Comment by SirForks** [comment]
> 
> 
> We still don't have support for BSC in AirGap, but the solution I posted above should still work.

Is this on the roadmap by chance?

**Comment by AndreasGassmann** [comment]
The latest release of AirGap Vault adds support for MetaMask. You can now use BSC and other EVM compatible chains by using AirGap Vault together with MetaMask: https://support.airgap.it/guides/metamask

We might still add support for BSC to AirGap Wallet, but because it's now possible to manage BSC with MetaMask, this has lower priority.

**Comment by AndreasGassmann** [comment]
Actually, because we don't have any concrete plans for now to add it, I will close this issue. Feel free to re-open if you think it should be in AirGap Wallet.

**Comment by martin-braun** [comment]
@AndreasGassmann We are currently launching an EVM compatible chain for a specialized use-case. Wondering if there are plans to bring support to EVM compatible chains in some foreseen future?

AirGap Wallet is wonderful and very straight-forward; and it can be used on the browser which makes it very handy. Obviously, it wouldn't be possible to display any FIAT value for our coins if there is no payment provider.

Is this something I could bring to Airgap by building an isolated module for each coin, too?
